---
- name: Deploy to tomcat
  hosts: web
  become: yes
  tasks:
  - name: Cop war file to tomcat
    copy:
     src: "/var/snap/jenkins/4865/workspace/MavenWebAppExt/target/MavenWebAppExt.war"
     dest: "/opt/tomcat/webapps/MavenWebAppExt.war"
     remote_src: no
     
  - name: Restart tomcat
    systemd:
     name: tomcat
     state: restarted
